### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by suprafun** [ShadwLink/Sketchup2GTA#36]
Hello, under what license is this project released under ? I would like to study it to learn more about SketchUp scripting. Thank-you.

**Comment by KilianSteenman** [comment]
Wowa, sorry about this. I had completely disabled notifications for this repository. I'll have to look into which license I can use, not sure if Sketchup forces a specific license, if not I'll try to chose one that allows as much as possible.

**Comment by KilianSteenman** [comment]
Added MIT license
