### ISSUE TITLE
When trying to import exported file into open IV I get open formats error:

### ISSUE THREAD

**Issue by Vatoka** [ShadwLink/Sketchup2GTA#37]
Got 31 expected 32

**Comment by KilianSteenman** [comment]
I haven't used this tool in a while. Might be that the format has changed or there is a bug in my exporter (most likely). Any chance you can share the exported file with me?

**Comment by KilianSteenman** [comment]
Closing this for now, feel free to re-open with more information or after I've created a new implementation.
