### ISSUE TITLE
How do I use this for GTA 5?

### ISSUE THREAD

**Issue by Suliure** [ShadwLink/Sketchup2GTA#46]
**Describe the bug**
I see this supports GTA V but when I attempt to select it I can't export anything?

**To Reproduce**
1. Open SketchUp file and I follow the correct to install the latest version but I can't select GTA V it says there's no support?

If you have a SketchUp file to reproduce the bug it would be great if you can include this too.

**Version info (please complete the following information):**
 - OS: [e.g. Windows 10]
 - SketchUp 2022
 - Plugin version 0.9.0

**Additional context**

**Comment by Suliure** [comment]
Yeah I've been trying, is there any support regarding it?

**Comment by KilianSteenman** [comment]
I did not work on re-adding V support yet. Can you explain whats going wrong when using 0.5.0?

**Comment by KilianSteenman** [comment]
More info required
